# TravisCI configuration for decodelabs/glitch

language: 'php'
os:
    - 'linux'
dist: 'bionic'

php:
    - '8.0'
    - '7.4'
    - '7.3'
    - '7.2'

cache:
    directories:
        - '${HOME}/.composer/cache'

before_install:
    - 'echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - 'composer validate --strict'

install:
    - 'composer update --no-interaction --prefer-dist'

script:
    - 'composer run-script analyze -- --no-interaction'
    - 'composer run-script psr12'
