language: php
php:
    - '7.2'
    - '7.3'

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --prefer-dist

script:
    - vendor/bin/phpstan analyse --no-interaction --no-progress
