# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrate"

on:
  push:
    branches:
      - "develop"
  pull_request: null

env:
  PHP_EXTENSIONS: "intl, :php-psr"

jobs:
  file_consistency:
    name: "1️⃣ File consistency"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.4"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "post_max_size=256M"

      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: Install Effigy
        run: |
          composer global config --no-plugins allow-plugins.phpstan/extension-installer true
          composer global config --no-plugins allow-plugins.decodelabs/genesis true
          composer global require decodelabs/effigy

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"

      - name: "Check coding style"
        run: |
          composer global exec effigy format -- --check --headless

      - name: "Check file permissions"
        run: |
          composer global exec effigy check-executable-permissions

      - name: "Check exported files"
        run: |
          composer global exec effigy check-git-exports

      - name: "Check EditorConfig configuration"
        run: "test -f .editorconfig"

      - name: "Check adherence to EditorConfig"
        uses: "greut/eclint-action@v0"

  static_analysis:
    name: "2️⃣ Static Analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.4"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "post_max_size=256M"

      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: Install Effigy
        run: |
          composer global config --no-plugins allow-plugins.phpstan/extension-installer true
          composer global config --no-plugins allow-plugins.decodelabs/genesis true
          composer global require decodelabs/effigy

      - name: "Validate Composer configuration"
        run: "composer validate --strict"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"

      - name: "Execute static analysis"
        run: |
          composer global exec effigy analyze -- --headless
